variable "client_id" {}
variable "client_secret" {}
variable "subscription_id" {}
variable "tenant_id" {}
variable "resource_group_name" {}
variable "location" {}
variable "virtual_network_address_space" {}
variable "web_subnet_prefix" {}
variable "app_subnet_prefix" {}
variable "db_subnet_prefix" {}
variable "bastion_subnet_prefix" {}
variable "application_gateway_subnet_prefix" {}
variable "web_nsg_ports" {}
variable "app_nsg_ports" {}
variable "db_nsg_ports" {}
variable "vm_username" {}
variable "db_admin_username" {}
variable "db_admin_password" {}
